const typeEnum = [
  "feat",
  "fix",
  "docs",
  "style",
  "refactor",
  "perf",
  "test",
  "build",
  "ci",
  "chore",
  "revert",
  "merge",
];

module.exports = {
  extends: ["@commitlint/config-conventional"],
  ignores: [(message) => message.startsWith("Merge ")],
  rules: {
    "type-enum": [2, "always", typeEnum],
    "scope-empty": [0],
    "subject-empty": [2, "never"],
    "subject-max-length": [2, "always", 114],
    "subject-full-stop": [2, "never", "."],
    "subject-case": [2, "never", ["sentence-case", "start-case", "pascal-case", "upper-case"]],
  },
  prompt: {
    messages: {
      type: "请选择提交类型:",
      scope: "请输入影响范围（可选）:",
      customScope: "请输入自定义影响范围:",
      subject: "请输入简短描述（必填）:",
      body: "请输入详细描述（可选，使用 | 换行）:",
      breaking: "请输入破坏性变更说明（可选，使用 | 换行）:",
      markBreaking: "是否存在破坏性变更（将在头部添加 !）？",
      footerPrefixesSelect: "请选择关联 Issue 前缀（可选）:",
      customFooterPrefix: "请输入自定义 Issue 前缀:",
      footer: "请输入关联的 Issue 号码（例如: #31, #34）:",
      confirmCommit: "确认提交以上内容？",
    },
    types: [
      { value: "feat", name: "feat:     新增功能" },
      { value: "fix", name: "fix:      修复缺陷" },
      { value: "docs", name: "docs:     仅文档变更" },
      { value: "style", name: "style:    代码风格/格式调整" },
      { value: "refactor", name: "refactor: 重构（无修复无新增）" },
      { value: "perf", name: "perf:     性能优化" },
      { value: "test", name: "test:     测试相关" },
      { value: "build", name: "build:    构建系统或依赖变更" },
      { value: "ci", name: "ci:       CI 配置或脚本变更" },
      { value: "chore", name: "chore:    日常维护或杂项" },
      { value: "revert", name: "revert:   回滚提交" },
      { value: "merge", name: "merge:    合并分支" },
    ],
    scopes: ["app", "ui", "config", "tooling", "docs", "tests", "ci"],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlias: "custom:   自定义",
    emptyScopesAlias: "empty:    不填写",
    allowBreakingChanges: ["feat", "fix"],
    issuePrefixes: [
      { value: "closed", name: "closed:   标记 ISSUES 已完成" },
      { value: "fixed", name: "fixed:    标记 ISSUES 已修复" },
    ],
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    customIssuePrefixAlias: "custom:   自定义前缀",
    emptyIssuePrefixAlias: "skip:     跳过",
    subjectLimit: 114,
  },
};
